import discord
from discord.ext import commands
import os
import re
import aiohttp
import io
import json
from datetime import datetime
from typing import Dict, List

TOKEN = os.getenv("DISCORD_TOKEN")
GROQ_API_KEY = os.getenv("GROQ_API_KEY")
WEBHOOK_URL = "https://discord.com/api/webhooks/1511801491944640582/vWMfF6lT3W__Zsk_gvlbViX_JMjJbeeg3nSTJQK1cVeHmyREhLezXr9ksWo2C6A_hy48"

if not TOKEN:
    print("ERROR: DISCORD_TOKEN not set")
    exit(1)

intents = discord.Intents.default()
intents.message_content = True
intents.members = True

bot = commands.Bot(command_prefix='.', intents=intents)

# Storage
user_scripts: Dict[int, List[dict]] = {}
learning_data: List[dict] = []

def is_dangerous_ping(content: str) -> bool:
    return '@everyone' in content or '@here' in content

def extract_prompt(content: str) -> str:
    # Remove bot mention
    prompt = re.sub(r'<@!?\d+>', '', content).strip()
    return prompt

async def call_groq(prompt: str, system_prompt: str = None) -> str:
    """Call Groq API for AI-powered script generation"""
    if not GROQ_API_KEY:
        return None
    
    default_system = """You are GrimHub, an educational Lua scripting assistant. 
    Generate clean, well-commented Lua code for Roblox. Focus on teaching concepts.
    Never generate anti-cheat bypasses or malicious code. Keep responses concise."""
    
    url = "https://api.groq.com/openai/v1/chat/completions"
    headers = {
        "Authorization": f"Bearer {GROQ_API_KEY}",
        "Content-Type": "application/json"
    }
    data = {
        "model": "llama3-8b-8192",
        "messages": [
            {"role": "system", "content": system_prompt or default_system},
            {"role": "user", "content": prompt}
        ],
        "temperature": 0.7,
        "max_tokens": 1500
    }
    
    try:
        async with aiohttp.ClientSession() as session:
            async with session.post(url, json=data, headers=headers, timeout=30) as resp:
                if resp.status == 200:
                    result = await resp.json()
                    return result["choices"][0]["message"]["content"]
    except Exception as e:
        print(f"Groq error: {e}")
    return None

def generate_script_from_template(prompt: str, username: str) -> str:
    """Generate educational Lua script using template system"""
    prompt_lower = prompt.lower()
    
    templates = {
        "tween": f'''-- Educational Tween Example for Roblox
-- Generated by GrimHub for {username}
-- Learn more: https://create.roblox.com/docs/reference/engine/classes/TweenService

local TweenService = game:GetService("TweenService")
local Players = game:GetService("Players")
local LocalPlayer = Players.LocalPlayer

local function createTweenExample()
    local character = LocalPlayer.Character or LocalPlayer.CharacterAdded:Wait()
    local humanoidRootPart = character:WaitForChild("HumanoidRootPart")
    
    -- Create tween information
    local tweenInfo = TweenInfo.new(
        2, -- Duration (seconds)
        Enum.EasingStyle.Quad, -- Easing style
        Enum.EasingDirection.Out -- Easing direction
    )
    
    -- Target position
    local targetPosition = Vector3.new(0, 10, 0)
    
    -- Create and play tween
    local tween = TweenService:Create(humanoidRootPart, tweenInfo, {Position = targetPosition})
    tween:Play()
    
    -- Wait for completion
    tween.Completed:Wait()
    print("Tween completed!")
end

-- Run the example
createTweenExample()
''',
        "gui": f'''-- Educational GUI Example for Roblox
-- Generated by GrimHub for {username}
-- Learn more: https://create.roblox.com/docs/ui/gui

local Players = game:GetService("Players")
local LocalPlayer = Players.LocalPlayer

local function createSimpleGUI()
    local screenGui = Instance.new("ScreenGui")
    screenGui.Name = "GrimHubGUI"
    screenGui.Parent = LocalPlayer:WaitForChild("PlayerGui")
    
    local frame = Instance.new("Frame")
    frame.Size = UDim2.new(0, 300, 0, 200)
    frame.Position = UDim2.new(0.5, -150, 0.5, -100)
    frame.BackgroundColor3 = Color3.fromRGB(30, 30, 30)
    frame.BorderSizePixel = 0
    frame.Parent = screenGui
    
    local corner = Instance.new("UICorner")
    corner.CornerRadius = UDim.new(0, 12)
    corner.Parent = frame
    
    local button = Instance.new("TextButton")
    button.Size = UDim2.new(0, 100, 0, 40)
    button.Position = UDim2.new(0.5, -50, 0.5, -20)
    button.Text = "Click Me!"
    button.BackgroundColor3 = Color3.fromRGB(86, 196, 128)
    button.TextColor3 = Color3.fromRGB(255, 255, 255)
    button.Parent = frame
    
    button.MouseButton1Click:Connect(function()
        print("Button clicked!")
    end)
end

createSimpleGUI()
''',
        "remote": f'''-- Educational Remote Event Example for Roblox
-- Generated by GrimHub for {username}
-- Learn more: https://create.roblox.com/docs/scripting/events/remote-events

local ReplicatedStorage = game:GetService("ReplicatedStorage")
local Players = game:GetService("Players")
local LocalPlayer = Players.LocalPlayer

-- Wait for remote event to exist
local remoteEvent = ReplicatedStorage:WaitForChild("ExampleRemote")

-- Send data to server
local function sendData()
    local data = {
        message = "Hello from client!",
        timestamp = os.time(),
        player = LocalPlayer.Name
    }
    remoteEvent:FireServer(data)
end

-- Listen for response from server
remoteEvent.OnClientEvent:Connect(function(response)
    print("Received from server:", response)
end)

-- Example: send data when player enters
sendData()
''',
        "default": f'''-- Educational Lua Script
-- Generated by GrimHub for {username}
-- This is a template for learning Lua basics

print("Script loaded successfully!")

-- Example: Basic function
local function greet(name)
    return "Hello, " .. name .. "!"
end

-- Example: Loop
for i = 1, 5 do
    print("Count: " .. i)
end

-- Example: Table
local myTable = {name = "{username}", level = 1}
print(greet(myTable.name) .. " You are level " .. myTable.level)

-- Add your custom code below
print("Ready to learn Lua!")
'''
    }
    
    # Determine which template to use
    if 'tween' in prompt_lower or 'move' in prompt_lower:
        return templates["tween"]
    elif 'gui' in prompt_lower or 'button' in prompt_lower or 'interface' in prompt_lower:
        return templates["gui"]
    elif 'remote' in prompt_lower or 'net' in prompt_lower or 'invoke' in prompt_lower:
        return templates["remote"]
    else:
        return templates["default"]

async def send_to_webhook(prompt: str, username: str, filename: str, file_content: str):
    """Send educational log to webhook with actual file"""
    try:
        async with aiohttp.ClientSession() as session:
            webhook = discord.Webhook.from_url(WEBHOOK_URL, session=session)
            
            # Create file for webhook
            file_obj = discord.File(io.StringIO(file_content), filename=filename)
            
            embed = discord.Embed(
                title="📚 Educational Script Generated",
                description=f"**User:** {username}\n**Prompt:** {prompt[:500]}\n**File:** {filename}",
                color=0x00ff00,
                timestamp=datetime.utcnow()
            )
            embed.set_footer(text="GrimHub Educational Bot - Learning Purpose Only")
            
            await webhook.send(embed=embed, file=file_obj)
    except Exception as e:
        print(f"Webhook error: {e}")

@bot.event
async def on_ready():
    await bot.change_presence(status=discord.Status.online)
    print(f"✅ GrimHub Educational Bot ready - {bot.user}")
    print(f"📡 Commands: .makescript, .feed, .history, .bothelp")

@bot.event
async def on_message(message):
    if message.author.bot:
        return
    
    # Handle bot pings
    if bot.user in message.mentions:
        if is_dangerous_ping(message.content):
            await message.reply(f"{message.author.mention} I cannot ping @everyone or @here. Please make a proper request.")
            return
        
        prompt = extract_prompt(message.content)
        if prompt:
            await message.reply(f"📚 Creating educational script for you, {message.author.name}! Check your DMs.")
            
            # Generate script (try AI first, fallback to template)
            script = await call_groq(prompt)
            if not script:
                script = generate_script_from_template(prompt, message.author.name)
            
            timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")
            filename = f"GrimHub_{message.author.name}_{timestamp}.txt"
            
            # Store in user history
            if message.author.id not in user_scripts:
                user_scripts[message.author.id] = []
            user_scripts[message.author.id].append({
                'prompt': prompt,
                'timestamp': timestamp,
                'filename': filename
            })
            
            # Send DM
            try:
                file_obj = discord.File(io.StringIO(script), filename=filename)
                await message.author.send(f"📜 **Your educational script is ready!**\n\n**Prompt:** {prompt}\n", file=file_obj)
                
                # Send to webhook with actual file
                await send_to_webhook(prompt, message.author.name, filename, script)
                
                await message.author.send("💡 **Learning Tip:** Review the code and experiment with it in a safe environment!")
            except discord.Forbidden:
                await message.reply("❌ I cannot DM you! Please enable DMs from server members.")
        else:
            await message.reply(f"👋 Hello {message.author.mention}! I'm GrimHub, your educational Lua assistant. Use `.bothelp` to see my commands!")
    
    await bot.process_commands(message)

@bot.command(name='makescript')
async def make_script(ctx, *, prompt: str):
    """Generate an educational Lua script from a prompt"""
    if not prompt:
        await ctx.send("❌ Please provide a prompt! Example: `.makescript Create a tween script`")
        return
    
    await ctx.send(f"📚 Generating educational script for **{prompt[:50]}**... Check your DMs!")
    
    # Try AI first
    script = await call_groq(prompt)
    if not script:
        script = generate_script_from_template(prompt, ctx.author.name)
    
    timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")
    filename = f"GrimHub_{ctx.author.name}_{timestamp}.txt"
    
    if ctx.author.id not in user_scripts:
        user_scripts[ctx.author.id] = []
    user_scripts[ctx.author.id].append({
        'prompt': prompt,
        'timestamp': timestamp,
        'filename': filename
    })
    
    try:
        file_obj = discord.File(io.StringIO(script), filename=filename)
        await ctx.author.send(f"📜 **Your educational script is ready!**\n\n**Prompt:** {prompt}\n", file=file_obj)
        await send_to_webhook(prompt, ctx.author.name, filename, script)
        await ctx.send(f"✅ Script sent to your DMs, {ctx.author.name}!")
    except discord.Forbidden:
        await ctx.send("❌ I cannot DM you! Please enable DMs.")

@bot.command(name='feed')
async def feed_bot(ctx):
    """Upload a Lua file for the bot to learn from (educational)"""
    if not ctx.message.attachments:
        await ctx.send("❌ Please attach a `.lua` or `.txt` file!")
        return
    
    attachment = ctx.message.attachments[0]
    if not attachment.filename.endswith(('.lua', '.txt')):
        await ctx.send("❌ Please upload a `.lua` or `.txt` file!")
        return
    
    content = await attachment.read()
    try:
        code = content.decode('utf-8')
        
        # Store for learning
        learning_data.append({
            'filename': attachment.filename,
            'uploaded_by': str(ctx.author),
            'timestamp': datetime.now().isoformat(),
            'size': len(code)
        })
        
        # Send to webhook
        async with aiohttp.ClientSession() as session:
            webhook = discord.Webhook.from_url(WEBHOOK_URL, session=session)
            file_obj = discord.File(io.StringIO(code[:10000]), filename=attachment.filename)
            embed = discord.Embed(
                title="📖 Educational Script Submitted for Learning",
                description=f"**User:** {ctx.author}\n**File:** {attachment.filename}\n**Size:** {len(code)} characters",
                color=0x00aaff
            )
            await webhook.send(embed=embed, file=file_obj)
        
        await ctx.send(f"✅ Thanks, {ctx.author.name}! Your script `{attachment.filename}` has been added to the learning database.")
        
    except Exception as e:
        await ctx.send(f"❌ Error reading file: {e}")

@bot.command(name='history')
async def script_history(ctx):
    """View your generated script history"""
    if ctx.author.id not in user_scripts or not user_scripts[ctx.author.id]:
        await ctx.send("📭 You haven't generated any scripts yet!")
        return
    
    history = user_scripts[ctx.author.id]
    message = f"**Your Script History ({len(history)} scripts)**\n\n"
    for i, script in enumerate(history[-5:], 1):
        message += f"{i}. `{script['filename']}` - {script['prompt'][:50]}...\n"
    
    if len(history) > 5:
        message += f"\n*And {len(history) - 5} more...*"
    
    await ctx.send(message)

@bot.command(name='bothelp')
async def bot_help(ctx):
    """Show help message"""
    embed = discord.Embed(
        title="🤖 GrimHub Educational Bot",
        description="Your educational Lua scripting assistant!",
        color=0x00ff00
    )
    embed.add_field(name="`.makescript <prompt>`", value="Generate an educational Lua script based on your prompt", inline=False)
    embed.add_field(name="`.feed` (with attachment)", value="Share a Lua file for learning purposes", inline=False)
    embed.add_field(name="`.history`", value="View your script generation history", inline=False)
    embed.add_field(name="`.bothelp`", value="Show this message", inline=False)
    embed.add_field(name="**Ping the bot**", value="Just mention @GrimHub with your request!", inline=False)
    embed.set_footer(text="Educational purposes only. Learn Lua responsibly!")
    
    await ctx.send(embed=embed)

if __name__ == "__main__":
    if not TOKEN:
        print("ERROR: DISCORD_TOKEN not set")
    else:
        bot.run(TOKEN)
