import discord
from discord.ext import commands
import os
import re
import aiohttp
import io
from datetime import datetime

TOKEN = os.getenv("DISCORD_TOKEN")

if not TOKEN:
    print("ERROR: DISCORD_TOKEN not set")
    exit(1)

intents = discord.Intents.default()
intents.message_content = True
intents.members = True

bot = commands.Bot(command_prefix='.', intents=intents)

user_scripts = {}

def is_dangerous_ping(content):
    return '@everyone' in content or '@here' in content

def extract_prompt(content):
    prompt = re.sub(r'<@!?\d+>', '', content).strip()
    return prompt

def generate_script(prompt, username):
    prompt_lower = prompt.lower()
    
    if 'tween' in prompt_lower:
        script = '-- Educational Tween Example\n'
        script += '-- Generated by GrimHub for ' + username + '\n\n'
        script += 'local TweenService = game:GetService("TweenService")\n'
        script += 'local Players = game:GetService("Players")\n'
        script += 'local LocalPlayer = Players.LocalPlayer\n'
        script += 'local character = LocalPlayer.Character or LocalPlayer.CharacterAdded:Wait()\n'
        script += 'local rootPart = character:WaitForChild("HumanoidRootPart")\n\n'
        script += 'local tweenInfo = TweenInfo.new(2, Enum.EasingStyle.Quad, Enum.EasingDirection.Out)\n'
        script += 'local targetPos = Vector3.new(0, 10, 0)\n'
        script += 'local tween = TweenService:Create(rootPart, tweenInfo, {Position = targetPos})\n'
        script += 'tween:Play()\n'
        script += 'tween.Completed:Wait()\n'
        script += 'print("Tween completed!")\n'
        return script
    
    elif 'gui' in prompt_lower:
        script = '-- Educational GUI Example\n'
        script += '-- Generated by GrimHub for ' + username + '\n\n'
        script += 'local Players = game:GetService("Players")\n'
        script += 'local LocalPlayer = Players.LocalPlayer\n'
        script += 'local screenGui = Instance.new("ScreenGui")\n'
        script += 'screenGui.Name = "GrimHubGUI"\n'
        script += 'screenGui.Parent = LocalPlayer:WaitForChild("PlayerGui")\n\n'
        script += 'local frame = Instance.new("Frame")\n'
        script += 'frame.Size = UDim2.new(0, 300, 0, 200)\n'
        script += 'frame.Position = UDim2.new(0.5, -150, 0.5, -100)\n'
        script += 'frame.BackgroundColor3 = Color3.fromRGB(30, 30, 30)\n'
        script += 'frame.Parent = screenGui\n\n'
        script += 'local button = Instance.new("TextButton")\n'
        script += 'button.Size = UDim2.new(0, 100, 0, 40)\n'
        script += 'button.Position = UDim2.new(0.5, -50, 0.5, -20)\n'
        script += 'button.Text = "Click Me!"\n'
        script += 'button.Parent = frame\n'
        script += 'button.MouseButton1Click:Connect(function()\n'
        script += '    print("Button clicked!")\n'
        script += 'end)\n'
        return script
    
    else:
        script = '-- Educational Lua Script\n'
        script += '-- Generated by GrimHub for ' + username + '\n\n'
        script += 'print("Script loaded successfully!")\n\n'
        script += 'local function greet(name)\n'
        script += '    return "Hello, " .. name .. "!"\n'
        script += 'end\n\n'
        script += 'for i = 1, 5 do\n'
        script += '    print("Count: " .. i)\n'
        script += 'end\n\n'
        script += 'print(greet("' + username + '"))\n'
        return script

@bot.event
async def on_ready():
    await bot.change_presence(status=discord.Status.online)
    print(f"GrimHub Bot ready - {bot.user}")
    print(f"Commands: .makescript, .bothelp")

@bot.event
async def on_message(message):
    if message.author.bot:
        return
    
    if bot.user in message.mentions:
        if is_dangerous_ping(message.content):
            await message.reply(f"{message.author.mention} No, I will not ping everyone.")
            return
        
        prompt = extract_prompt(message.content)
        if prompt:
            await message.reply(f"Creating script for {message.author.name}! Check your DMs.")
            
            script = generate_script(prompt, message.author.name)
            timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")
            filename = f"GrimHub_{message.author.name}_{timestamp}.txt"
            
            if message.author.id not in user_scripts:
                user_scripts[message.author.id] = []
            user_scripts[message.author.id].append({
                'prompt': prompt,
                'timestamp': timestamp,
                'filename': filename
            })
            
            try:
                file_obj = discord.File(io.StringIO(script), filename=filename)
                await message.author.send(f"Your script is ready!\n\nPrompt: {prompt}\n", file=file_obj)
                await message.reply("Script sent to your DMs!")
            except discord.Forbidden:
                await message.reply("I cannot DM you! Please enable DMs.")
        else:
            await message.reply(f"Hello {message.author.mention}! Use .bothelp to see commands.")
    
    await bot.process_commands(message)

@bot.command(name='makescript')
async def make_script(ctx, *, prompt):
    if not prompt:
        await ctx.send("Please provide a prompt. Example: .makescript Create a tween script")
        return
    
    await ctx.send(f"Generating script... Check your DMs!")
    
    script = generate_script(prompt, ctx.author.name)
    timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")
    filename = f"GrimHub_{ctx.author.name}_{timestamp}.txt"
    
    if ctx.author.id not in user_scripts:
        user_scripts[ctx.author.id] = []
    user_scripts[ctx.author.id].append({
        'prompt': prompt,
        'timestamp': timestamp,
        'filename': filename
    })
    
    try:
        file_obj = discord.File(io.StringIO(script), filename=filename)
        await ctx.author.send(f"Your script is ready!\n\nPrompt: {prompt}\n", file=file_obj)
        await ctx.send(f"Script sent to your DMs, {ctx.author.name}!")
    except discord.Forbidden:
        await ctx.send("I cannot DM you! Please enable DMs.")

@bot.command(name='history')
async def script_history(ctx):
    if ctx.author.id not in user_scripts or not user_scripts[ctx.author.id]:
        await ctx.send("You haven't generated any scripts yet!")
        return
    
    history = user_scripts[ctx.author.id]
    message = f"Your Script History ({len(history)} scripts)\n\n"
    for i, script in enumerate(history[-5:], 1):
        message += f"{i}. {script['filename']}\n"
    
    await ctx.send(message)

@bot.command(name='bothelp')
async def bot_help(ctx):
    embed = discord.Embed(
        title="GrimHub Bot",
        description="Your Lua scripting assistant!",
        color=0x00ff00
    )
    embed.add_field(name=".makescript <prompt>", value="Generate a Lua script", inline=False)
    embed.add_field(name=".history", value="View your script history", inline=False)
    embed.add_field(name=".bothelp", value="Show this help", inline=False)
    embed.add_field(name="Ping the bot", value="Mention @GrimHub with your request!", inline=False)
    
    await ctx.send(embed=embed)

if __name__ == "__main__":
    bot.run(TOKEN)
